# Generated by Django 5.2 on 2025-04-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='plants', to='main_app.recipe'),
        ),
    ]
