# Generated by Django 5.2 on 2025-04-29 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_plant_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_recipes', to='main_app.plant'),
        ),
    ]
